### ISSUE TITLE
problem on loading image

### ISSUE THREAD

**Issue by wulianlhc** [OpenPIV/openpiv-matlab#26]
I run the code under matlab 2013a and 2014a； when loaing test image to the GUI, there will be sereval errors showing below:

>> openpivgui
Index exceeds matrix dimensions.

Error in openpivgui>ReadImageDirectory (line 898)
firstDif = find(handles.files{2}-handles.files{1},1,'first'); % how the
first two files are different?

Error in openpivgui>load_Callback (line 410)
handles = ReadImageDirectory(handles);

Error in gui_mainfcn (line 96)
        feval(varargin{:});

Error in openpivgui (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)openpivgui('load_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating uimenu Callback

What's the reason???

**Comment by alexlib** [comment]
I guess it's something related to the fact that the last version is for 2014b and later. Please check this version: 

https://github.com/OpenPIV/openpiv-matlab/releases

**Comment by wulianlhc** [comment]
I got it. Thanks!



wulianlhc@163.com
 
From: Alex Liberzon
Date: 2017-09-09 01:01
To: OpenPIV/openpiv-matlab
CC: wulianlhc; Author
Subject: Re: [OpenPIV/openpiv-matlab] problem on loading image (#26)
I guess it's something related to the fact that the last version is for 2014b and later. Please check this version:
https://github.com/OpenPIV/openpiv-matlab/releases

**Comment by widyananda** [comment]
Hallo,
Could somebody help me? I am really a newbie here. So, I have downloaded all of the files of OpenPIV_Spatial_toolbox from http://www.openpiv.net/openpiv-spatial-analysis-toolbox/ . My Matlab is 2018a version. When I want to load the .mat files and .txt files, it only read one file and give me the answer **Reference to non-existent field 'x'**.
I have 600 files.

However, it worked properly for .vec files. I have searched the solution and mostly stated there is something I have to do with GUI. But I cannot even find GUI files in Spatialbox.

I don't know whether I explain it well, I hope somebody can help me.

Thank you
Regards,
Suwito

**Comment by alexlib** [comment]
Hi, 

let's check one thing at a time. Since I do not have an access to Matlab 2018a version, some things we'll need to check on your computer (via teamviewer for instance). 

please share your .mat and .txt files so I could test it on another computer/Matlab version.

**Comment by widyananda** [comment]
Thank you for your fast reply,

I tried the **test_mat** and **test_txt** files from the downloaded files from  http://www.openpiv.net/openpiv-spatial-analysis-toolbox/ but they did not work either. If you may possible to try on Matlab 2017b or 2018a, which both gave me the same problems, I really appreciate it.

Thank you again and looking forward to your help.
Best Regards,
Suwito

**Comment by alexlib** [comment]
Unfortunately I do not have an access to newer Matlab versions. if you share a teamviewer access to your machine, I may try.

**Comment by widyananda** [comment]
I really appreciate your time and help. May I know when do you have time?

**Comment by alexlib** [comment]
let's discuss it over e-mail. send to openpiv2008@gmail.com the time you're available and your time zone. I'm at GMT+3 and might have some time to check it this evening, e.g. in 6-7 hrs from now.

**Comment by alexlib** [comment]
I've got 2018a to test - please: 

1. move the discussion to the issues on openpiv-spatialbox here: https://github.com/OpenPIV/openpiv-spatial-analysis-toolbox/issues

2. please upload 10 txt files for a test

**Comment by widyananda** [comment]
Halo @alexlib 

I have sent you an email. Kindly check it. Thank you.

**Comment by alexlib** [comment]
try 
https://github.com/OpenPIV/openpiv-matlab/pull/28
