### ISSUE TITLE
Number of errors in openpivgui

### ISSUE THREAD

**Issue by markattard95** [OpenPIV/openpiv-matlab#27]
Hi,

I have a number of errors that are popping up using both 'openpiv-matlab-master' and 'openpiv-matlab-1.1' on different versions of Matlab.

![capture](https://user-images.githubusercontent.com/31954705/30422651-e0b86a16-9940-11e7-88c1-4361c97379e9.PNG)
![capture2](https://user-images.githubusercontent.com/31954705/30422650-e0b795be-9940-11e7-9297-0c33d649f5b9.PNG)

The errors read as follows 'Input argument 'xxxxx' might be unused. If this is OK, consider replacing it by ~.' where xxxxx are the highlighted variables in the above print screen.

Thanks.

**Comment by alexlib** [comment]
`imshow` is a function from Image Processing Toolbox of Matlab. Make sure you have it installed or move to Python :)

**Comment by markattard95** [comment]
Hi :) sorry for my late reply but thanks for your prompt response. 

I did install the IPT for Matlab but still some errors prevail. Please find the errors encountered here under.

_> Index exceeds matrix dimensions.
> 
> Error in openpivgui>ReadImageDirectory (line 898)
> firstDif = find(handles.files{2}-handles.files{1},1,'first'); % how the first two files are different?
> 
> Error in openpivgui>load_Callback (line 410)
> handles = ReadImageDirectory(handles);
> 
> Error in gui_mainfcn (line 95)
>         feval(varargin{:});
> 
> Error in openpivgui (line 42)
>     gui_mainfcn(gui_State, varargin{:});
> 
> Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)openpivgui('load_Callback',hObject,eventdata,guidata(hObject))
>  
> Error while evaluating Menu Callback
> 
> Index exceeds matrix dimensions.
> 
> Error in openpivgui>ReadImageDirectory (line 898)
> firstDif = find(handles.files{2}-handles.files{1},1,'first'); % how the first two files are different?
> 
> Error in openpivgui>load_Callback (line 410)
> handles = ReadImageDirectory(handles);
> 
> Error in gui_mainfcn (line 95)
>         feval(varargin{:});
> 
> Error in openpivgui (line 42)
>     gui_mainfcn(gui_State, varargin{:});
> 
> Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)openpivgui('load_Callback',hObject,eventdata,guidata(hObject))
>  
> Error while evaluating Menu Callback
> 
> Reference to non-existent field 'path'.
> 
> Error in openpiv_imread (line 12)
>     tmp = tiffread2(fullfile(handles.path,handles.files{filenum}));
> 
> Error in read_pair_of_images_rect (line 26)
>     A = openpiv_imread(handles,fileind); % ,'tif'); 8 June 2005, no extension is necessary
> 
> Error in openpivgui>pushbutton_start_Callback (line 469)
> [a,b] = read_pair_of_images_rect(handles,1,1,cropvec,ittWidth,ittHeight,ovlapHor,ovlapVer);
> 
> Error in gui_mainfcn (line 95)
>         feval(varargin{:});
> 
> Error in openpivgui (line 42)
>     gui_mainfcn(gui_State, varargin{:});
> 
> Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)openpivgui('pushbutton_start_Callback',hObject,eventdata,guidata(hObject))
>  
> Error while evaluating UIControl Callback_ 

Truly appreciate your help.

**Comment by markattard95** [comment]
I would like to add that these errors arise when I load the images into the software (the test images). I tried to convert them to .PNG format and load those but the same errors still persisted.

**Comment by alexlib** [comment]
Please, post here an output of `ver` of your Matlab. 

>> ver

>> ver
----------------------------------------------------------------------------------------------------
MATLAB Version: 8.4.0.150421 (R2014b)
Operating System: Mac OS X  Version: 10.12.6 Build: 16G29 
Java Version: Java 1.7.0_55-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
----------------------------------------------------------------------------------------------------
MATLAB                                                Version 8.4        (R2014b)
Simulink                                              Version 8.4        (R2014b)
Computer Vision System Toolbox                        Version 6.1        (R2014b)
Control System Toolbox                                Version 9.8        (R2014b)
Curve Fitting Toolbox                                 Version 3.5        (R2014b)
Image Acquisition Toolbox                             Version 4.8        (R2014b)
Image Processing Toolbox                              Version 9.1        (R2014b)
MATLAB Builder JA                                     Version 2.3.2      (R2014b)
MATLAB Coder                                          Version 2.7        (R2014b)
MATLAB Compiler                                       Version 5.2        (R2014b)
MATLAB Report Generator                               Version 4.0        (R2014b)
Optimization Toolbox                                  Version 7.1        (R2014b)
PIVMat Toolbox                                        Version 3.03               
Parallel Computing Toolbox                            Version 6.5        (R2014b)
Partial Differential Equation Toolbox                 Version 1.5        (R2014b)
Signal Processing Toolbox                             Version 6.22       (R2014b)
Statistics Toolbox                                    Version 9.1        (R2014b)
Symbolic Math Toolbox                                 Version 6.1        (R2014b)

**Comment by alexlib** [comment]
which test images do you try to load? 

1. `test1`
2. `test2`
3. `test3`

**Comment by alexlib** [comment]
I cannot reproduce this problem on Windows 10 or Mac OS X. Please send me a private e-mail with the teamviewer ID and password and time that I can login your machine to find the origin of the problem.
