### ISSUE TITLE
Error of analysis

### ISSUE THREAD

**Issue by widyananda** [OpenPIV/openpiv-matlab#29]
Dear all,

I am running the jpg file. From 600 pictures that I had, 500 were successfully analyzed but it comes to this error when reaching the 500th pictures. Any solution is appreciated.

Have a good day,

_Operands to the || and && operators must be convertible to logical scalar values.

Error in find_displacement_rect (line 47)
        if x2 > 1 && y2 > 1 && x2 < NfftHeight && y2 < NfftWidth

Error in openpivgui>openpiv_main_loop (line 1036)
        [peak1,peak2,pixi,pixj] = find_displacement_rect(c,s2ntype);

Error in openpivgui>pushbutton_start_Callback (line 477)
            openpiv_main_loop(handles, fileind, jump, cropvec,ittWidth,...

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in openpivgui (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)openpivgui('pushbutton_start_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback._

**Comment by alexlib** [comment]
please upload somewhere the images pair that creates the problem. the error seems to do nothing with the number of images.
