### ISSUE TITLE
Analysis Never Finishes

### ISSUE THREAD

**Issue by maxcw** [OpenPIV/openpiv-matlab#31]
I'm trying to use OpenPIV for the first time. In the GUI, I selected two images from /test1, and selected a small ROI. When clicking "Start" the wheel spins forever. I have MATLAB version 2018, so I'm not sure what the problem is. I did not adjust any of the default settings.

**Comment by alexlib** [comment]
this is unexpected error that is not reproduced on my computer. can we talk or connect to your machine to see what's wrong?

**Comment by alexlib** [comment]
I downloaded now the latest version and it runs fine on the test images. Please tell what's wrong on your side @maxcw

**Comment by alexlib** [comment]
@maxcw  please see https://github.com/alexlib/openpiv-matlab/tree/2018a
