### ISSUE TITLE
here is a bug that was found before in #7

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv-matlab#34]
https://github.com/OpenPIV/openpiv-matlab/blob/c540825698efa84f3fb6ea1eef06b7a7df241986/openpivgui.m#L1032

**Comment by chinajiang99** [comment]
Thanks, I have received your mail.

----
Best Regards，





 




--





SCHOOL OF CIVIL ENGINEERING,

TIANJIN CHENGJIAN UNIVERSITY

 

JIANG XUE-LIAN   Ph.D.

 

Email：jiang.xuelian@tcu.edu.cn; jiangxuelian99@163.com  

Mb:008613802075165

Address: No.26, Jinjing Rd., Xiqing District, Tianjin , P.R.China





zip code:300384
--

 

天津城建大学土木工程学院 蒋学炼

 

邮箱: jiang.xuelian@tcu.edu.cn; jiangxuelian99@163.com  

手机: 13802075165

地址：中国天津市西青区津静公路26号

邮编：300384


--

博学之，审问之，慎思之，明辨之，笃行之。
