### ISSUE TITLE
unable to uplaod images

### ISSUE THREAD

**Issue by szs0196** [OpenPIV/openpiv-matlab#37]
When i try to upload images get the following error

Error using openpiv_imread
Too many input arguments.

Error in openpivgui>load_Callback (line 406)
im = openpiv_imread(handles,1);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in openpivgui (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)openpivgui('load_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating Menu Callback.

May feel dumb but will appreciate help

**Comment by szs0196** [comment]
I am using Matlab 20186

**Comment by alexlib** [comment]
@szs0196 please see the branch called https://github.com/alexlib/openpiv-matlab/tree/2018a

**Comment by alexlib** [comment]
or maybe better move to openpiv-python :)
